# Generated by Django 5.2.15 on 2026-07-03 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taxonomies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marketplace",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=100, unique=True)),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("base_url", models.URLField(unique=True)),
                ("base_search_url", models.URLField()),
                ("categorised_search_url", models.URLField(blank=True, null=True)),
                (
                    "index_output",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_suspended", models.BooleanField(default=False)),
                ("is_running", models.BooleanField(default=False)),
                (
                    "currency",
                    models.ManyToManyField(blank=True, to="taxonomies.currency"),
                ),
                (
                    "region_boundary",
                    models.ManyToManyField(blank=True, to="taxonomies.country"),
                ),
            ],
        ),
    ]
