# Generated by Django 5.2.15 on 2026-06-28 23:26

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InternalMerchantProfile",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("shopName", models.CharField(db_index=True, max_length=255)),
                ("shopDescription", models.TextField(blank=True, null=True)),
                (
                    "accountEmail",
                    models.EmailField(
                        help_text="Administrative business email for financial and billing workflows.",
                        max_length=254,
                    ),
                ),
                (
                    "shop_logo_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "shop_banner_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "is_accepting_orders",
                    models.BooleanField(
                        default=True, help_text="Store vacation mode or temporary pause"
                    ),
                ),
                (
                    "shopCategory",
                    models.CharField(
                        choices=[
                            ("Electronics", "Electronics, Gadgets & Appliances"),
                            ("GeneralShop", "General Store (All kinds of goods)"),
                            ("Clothing Apparel", "Clothing, Fashion & Accessories"),
                            ("Grocery Food", "Groceries, Supermarkets & Fresh Food"),
                            ("Health Beauty", "Health, Beauty & Cosmetics"),
                            ("Home Decor", "Home Decor, Furniture & Living"),
                            (
                                "Automotive Parts",
                                "Automotive Parts, Tools & Accessories",
                            ),
                            ("Books Stationery", "Books, Stationery & Office Supplies"),
                            ("Sports Outdoors", "Sports, Fitness & Outdoor Gear"),
                            ("Toys Hobbies", "Toys, Games & Hobby Supplies"),
                            (
                                "Pharmacy Medical",
                                "Pharmacy, Medicine & Medical Supplies",
                            ),
                            ("Pet Supplies", "Pet Food, Toys & Pet Care"),
                            (
                                "Hardware Construction",
                                "Hardware, Tools & Construction Materials",
                            ),
                            ("Restaurant Cafe", "Restaurants, Cafes & Prepared Food"),
                        ],
                        default="GeneralShop",
                        max_length=200,
                    ),
                ),
                ("bussinessRegisted", models.BooleanField(default=False)),
                (
                    "taxPin",
                    models.CharField(
                        blank=True,
                        help_text="e.g., KRA PIN for tax compliance",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "businessRegistrationNumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "support_phone",
                    models.CharField(
                        blank=True,
                        help_text="Customer-facing support number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "commissionCutPercent",
                    models.DecimalField(
                        decimal_places=3,
                        default=3.505,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("totalActiveListings", models.PositiveIntegerField(default=0)),
                ("isCommissionFree", models.BooleanField(default=False)),
                (
                    "verificationStatus",
                    models.CharField(
                        choices=[
                            ("verified", "Verified Active"),
                            ("pending_review", "Pending Review"),
                            ("suspended", "Suspended Hold"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                (
                    "payoutMethod",
                    models.CharField(
                        choices=[
                            ("M-Pesa", "M-Pesa"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Card Settlement", "Card Settlement"),
                        ],
                        default="M-Pesa",
                        max_length=25,
                    ),
                ),
                (
                    "bankAccountNumber",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("bankName", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "payBillNumber",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "accountNumber",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "accountPhone",
                    models.CharField(
                        help_text="Bussiness Phone number for financial ", max_length=13
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Internal Merchant Profile",
                "verbose_name_plural": "Internal Merchant Profiles",
                "db_table": "soko_internal_merchant_profile",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="MerchantActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication & Security"),
                            ("profile", "Profile & Settings Modification"),
                            ("branch", "Branch Distribution Operations"),
                            ("catalog", "Inventory & Catalog Updates"),
                            ("order", "Order & Fulfillment Triggers"),
                            ("payout", "Financials & Ledger Settlements"),
                            ("system", "System Automation / Background Alert"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("warning", "Warning Notice"),
                            ("critical", "Critical Security/Financial"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=15,
                    ),
                ),
                (
                    "action_event",
                    models.CharField(
                        help_text="e.g., 'user_login', 'order_received_alert', 'order_rejected', 'branch_created'",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable detail statement summarizing exactly what transpired."
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser/device fingerprint data",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "location_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Approximate or pinpoint geo-metadata at the moment of entry, e.g., 'Juja, Kiambu'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "linked_order_uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Reference to the related MerchantOrder if applicable",
                        null=True,
                    ),
                ),
                (
                    "linked_product_uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Reference to the related MerchantProductCatalog if applicable",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Merchant Activity Log",
                "verbose_name_plural": "Merchant Activity Logs",
                "db_table": "soko_merchant_activity_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchantInventoryStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantityInStock", models.PositiveIntegerField(default=0)),
                ("lowStockThreshold", models.PositiveIntegerField(default=5)),
                (
                    "reservedQuantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Stock currently locked in active orders but not yet shipped",
                    ),
                ),
                (
                    "shelfLocation",
                    models.CharField(
                        blank=True,
                        help_text="Warehouse bin/shelf identifier (e.g., Aisle 4, Bin B)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("lastRestocked", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "soko_merchant_inventory_stock",
            },
        ),
        migrations.CreateModel(
            name="MerchantOrder",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AWAITING_ALLOCATION", "Awaiting System Processing"),
                            ("PREPARING", "Picking & Packing Items"),
                            ("READY_FOR_PICKUP", "Package Ready at Branch Hub"),
                            ("DISPATCHED", "Handed over to Carrier/Rider"),
                            ("DELIVERED", "Successfully Delivered to Customer"),
                            ("CANCELLED", "Order Cancelled"),
                            ("DISPUTED", "Disputed / Hold on Payout"),
                            ("REFUNDED", "Returned & Refunded"),
                        ],
                        db_index=True,
                        default="AWAITING_ALLOCATION",
                        max_length=30,
                    ),
                ),
                (
                    "waybillNumber",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Tracking code for the logistics dispatch runner (e.g., Sendy, Fargo, Boda rider).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "isUrgent",
                    models.BooleanField(
                        default=False,
                        help_text="Bypass standard batch queues (e.g., fresh foods, medical essentials)",
                    ),
                ),
                (
                    "requiresColdChain",
                    models.BooleanField(
                        default=False,
                        help_text="Requires refrigerated dispatch routing",
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=100)),
                (
                    "grossSalesAmount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total revenue generated from items sold",
                        max_digits=12,
                    ),
                ),
                (
                    "shippingAllocation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Shipping fee portion paid out to the vendor if self-fulfilled",
                        max_digits=12,
                    ),
                ),
                (
                    "taxAllocation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Vatable amount collected for this merchant branch",
                        max_digits=12,
                    ),
                ),
                (
                    "commissionPercentageApplied",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Snapshot of the platform take rate applied.",
                        max_digits=5,
                    ),
                ),
                (
                    "platformFeeDeducted",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Platform commission fee deducted from gross sales.",
                        max_digits=12,
                    ),
                ),
                (
                    "netVendorPayout",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        help_text="The final net earnings added to the merchant's withdrawable ledger balance.",
                        max_digits=12,
                    ),
                ),
                (
                    "shippingCustomerName",
                    models.CharField(
                        help_text="Name printed on the packing slip", max_length=255
                    ),
                ),
                ("shippingPhone", models.CharField(max_length=20)),
                ("shippingCounty", models.CharField(max_length=100)),
                ("shippingTown", models.CharField(max_length=100)),
                (
                    "shippingPhysicalAddress",
                    models.TextField(
                        help_text="Detailed drop-off coordinates or building/estate details."
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Merchant Order Execution",
                "verbose_name_plural": "Merchant Order Executions",
                "db_table": "soko_merchant_order",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="MerchantOrderItem",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("productTitle", models.CharField(max_length=255)),
                (
                    "productSku",
                    models.CharField(
                        blank=True,
                        help_text="Vendor inventory SKU for picker verification",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "shelfLocationSnapshot",
                    models.CharField(
                        blank=True,
                        help_text="Where the picker can locate the item inside the branch hub",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "unitPriceAtSale",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "quantityOrdered",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Order Manifest Item",
                "verbose_name_plural": "Merchant Order Manifest Items",
                "db_table": "soko_merchant_order_item",
            },
        ),
        migrations.CreateModel(
            name="MerchantPayoutLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "linked_order_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the SubOrder that generated this payout",
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=10)),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total revenue generated before cut",
                        max_digits=12,
                    ),
                ),
                (
                    "platform_cut_applied",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The snapshot commissionCutPercent applied",
                        max_digits=5,
                    ),
                ),
                (
                    "net_payout_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount sent to merchant after take rate deduction",
                        max_digits=12,
                    ),
                ),
                ("payout_channel", models.CharField(default="M-Pesa", max_length=30)),
                (
                    "payout_destination",
                    models.CharField(
                        help_text="Paybill/Till Number, Phone Number, or Account Number",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Processing Processing"),
                            ("completed", "Completed Settled"),
                            ("failed", "Failed Reverted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True,
                        help_text="External gateway transaction ID",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for failed/disputed payouts",
                        null=True,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "soko_merchant_payout_ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchantProductCatalog",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Merchant's Stock Keeping Unit identifier",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("isRefubished", models.BooleanField(default=False)),
                ("isNew", models.BooleanField(default=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL friendly title",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "userAddedsearchTags",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated keywords",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "originalPrice",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "dealPrice",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Active selling price",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "priceChangeRecord",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="record of all prices this product has had",
                        null=True,
                    ),
                ),
                (
                    "priceComPetitonRecord",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="position in pricing and the defference from the most selling merchant",
                        null=True,
                    ),
                ),
                (
                    "weightKg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Crucial for calculating shipping rates",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "isPhysical",
                    models.BooleanField(
                        default=True, help_text="False for digital downloads/services"
                    ),
                ),
                ("isTaxExempt", models.BooleanField(default=False)),
                ("primaryIimageUrl", models.URLField(max_length=500)),
                (
                    "secondaryImages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of supplemental image strings",
                    ),
                ),
                ("isAvailable", models.BooleanField(db_index=True, default=True)),
                (
                    "clickCount",
                    models.PositiveIntegerField(
                        default=0, help_text="Tracks user engagement"
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "soko_merchant_product_catalog",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="MerchantStoreBranch",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("branchName", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("county", models.CharField(default="Kiambu", max_length=100)),
                ("cityTown", models.CharField(default="Juja", max_length=100)),
                (
                    "physicalAddress",
                    models.TextField(
                        help_text="Detailed location info, e.g., Thika Road Mall, 2nd Floor"
                    ),
                ),
                (
                    "isPrimary",
                    models.BooleanField(
                        default=False,
                        help_text="Main fulfillment center for default routing",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="For last-mile delivery API routing",
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                    ),
                ),
                ("opens", models.TimeField(blank=True, null=True)),
                ("closes", models.TimeField(blank=True, null=True)),
                (
                    "operatingHours",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Mon-Sat: 8AM-6PM'",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Merchant Store Branches",
                "db_table": "soko_merchant_branch",
            },
        ),
    ]
