# Generated by Django 5.2.15 on 2026-07-13 21:50

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankTransfarMerchnatPayoutDestination",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(default="Bank Transfar", max_length=200)),
                ("accountNumber", models.CharField(max_length=15, null=True)),
                ("isActive", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DailyGrossSalesSnapshot",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "gross_sales_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total revenue generated before any deductions",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "soko_merchant_gross_sales_snapshot",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InternalMerchantProfile",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("vendorCode", models.CharField(blank=True, max_length=200, null=True)),
                ("shopName", models.CharField(db_index=True, max_length=255)),
                ("shopDescription", models.TextField(blank=True, null=True)),
                (
                    "accountEmail",
                    models.EmailField(
                        help_text="Administrative business email for financial and billing workflows.",
                        max_length=254,
                    ),
                ),
                (
                    "accountPhone",
                    models.CharField(
                        blank=True,
                        help_text="Customer-facing support number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "shopLogoPlaceHolder",
                    models.URLField(blank=True, default="", null=True),
                ),
                (
                    "shopBannerPlaceHolder",
                    models.URLField(blank=True, default="", null=True),
                ),
                (
                    "shopLogo",
                    models.ImageField(
                        blank=True, null=True, upload_to="Merchants/ShopLogos/"
                    ),
                ),
                (
                    "shopBanner",
                    models.ImageField(
                        blank=True, null=True, upload_to="Merchants/ShopBanners/"
                    ),
                ),
                (
                    "is_accepting_orders",
                    models.BooleanField(
                        default=True, help_text="Store vacation mode or temporary pause"
                    ),
                ),
                (
                    "shopCategory",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "shopCategoryPersist",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bussinessRegisted", models.BooleanField(default=False)),
                (
                    "taxPin",
                    models.CharField(
                        blank=True,
                        help_text="e.g., KRA PIN for tax compliance",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "businessRegistrationNumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "legalDocument",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Merchants/BusinessVerificationDocuments/",
                    ),
                ),
                (
                    "commissionCutPercent",
                    models.DecimalField(
                        decimal_places=3,
                        default=3.505,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("totalActiveListings", models.PositiveIntegerField(default=0)),
                ("isCommissionFree", models.BooleanField(default=False)),
                (
                    "verificationStatus",
                    models.CharField(
                        choices=[
                            ("verified", "Verified Active"),
                            ("pending_review", "Pending Review"),
                            ("suspended", "Suspended Hold"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "payoutMethod",
                    models.CharField(
                        choices=[
                            ("M-Pesa", "M-Pesa"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Card Settlement", "Card Settlement"),
                        ],
                        default="M-Pesa",
                        max_length=25,
                    ),
                ),
                (
                    "bankAccountNumber",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("bankName", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "payBillNumber",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "accountNumber",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "sendMoneyPhone",
                    models.CharField(
                        blank=True,
                        help_text="Bussiness Phone number for financial ",
                        max_length=13,
                        null=True,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Internal Merchant Profile",
                "verbose_name_plural": "Internal Merchant Profiles",
                "db_table": "soko_internal_merchant_profile",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="MerchantActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication & Security"),
                            ("profile", "Profile & Settings Modification"),
                            ("branch", "Branch Distribution Operations"),
                            ("catalog", "Inventory & Catalog Updates"),
                            ("order", "Order & Fulfillment Triggers"),
                            ("payout", "Financials & Ledger Settlements"),
                            ("system", "System Automation / Background Alert"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("warning", "Warning Notice"),
                            ("critical", "Critical Security/Financial"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=15,
                    ),
                ),
                (
                    "action_event",
                    models.CharField(
                        help_text="e.g., 'user_login', 'order_received_alert', 'order_rejected', 'branch_created'",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable detail statement summarizing exactly what transpired."
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser/device fingerprint data",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "location_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Approximate or pinpoint geo-metadata at the moment of entry, e.g., 'Juja, Kiambu'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "linked_order_uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Reference to the related MerchantOrder if applicable",
                        null=True,
                    ),
                ),
                (
                    "linked_product_uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Reference to the related MerchantProductCatalog if applicable",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Merchant Activity Log",
                "verbose_name_plural": "Merchant Activity Logs",
                "db_table": "soko_merchant_activity_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchantAlert",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "Type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("system", "System Alert"),
                            ("order", "Order Alert"),
                            ("inventory", "Inventory Alert"),
                            ("payout", "Payout Alert"),
                            ("profile", "Profile Alert"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("Message", models.TextField(blank=True, null=True)),
                (
                    "Priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("Read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MerchantInventory",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inventoryID", models.UUIDField(default=uuid.uuid4)),
                (
                    "inventoryTitle",
                    models.CharField(default="Main Inventory", max_length=200),
                ),
                (
                    "inventoryDescription",
                    models.TextField(default="Main inventory for your shop"),
                ),
                ("inventoryActive", models.BooleanField(default=True)),
                ("inventoryLocked", models.BooleanField(default=False)),
                ("totalProducts", models.PositiveIntegerField(default=0)),
                ("totalInventoryValue", models.PositiveIntegerField(default=0)),
                ("lowStockItems", models.PositiveIntegerField(default=0)),
                ("outOfStockItems", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="MerchantInventoryProduct",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("productDef", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "productCode",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Merchant's Stock Keeping Unit identifier",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=200, null=True)),
                ("brand", models.CharField(blank=True, max_length=200, null=True)),
                ("color", models.CharField(blank=True, max_length=200, null=True)),
                ("size", models.CharField(blank=True, max_length=200, null=True)),
                ("shape", models.CharField(blank=True, max_length=200, null=True)),
                ("length", models.FloatField(blank=True, null=True)),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                (
                    "weightKg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Crucial for calculating shipping rates",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "isPhysical",
                    models.BooleanField(
                        default=True, help_text="False for digital downloads/services"
                    ),
                ),
                ("isNew", models.BooleanField(default=True)),
                ("isUsable", models.BooleanField(default=True)),
                ("isRefurbished", models.BooleanField(default=False)),
                ("isSecondHand", models.BooleanField(default=False)),
                ("isDamaged", models.BooleanField(default=False)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("madeIn", models.CharField(blank=True, max_length=200, null=True)),
                ("locallyMade", models.BooleanField(default=False)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL friendly title",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("searchTerms", models.JSONField(blank=True, default=list, null=True)),
                ("tags", models.JSONField(blank=True, default=list, null=True)),
                (
                    "originalPrice",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "recentPrice",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "dealPrice",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Active selling price",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "priceChangeRecords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="record of all prices this product has had",
                        null=True,
                    ),
                ),
                (
                    "priceCompetitionRecords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="position in pricing and the defference from the most selling merchant",
                        null=True,
                    ),
                ),
                ("isTaxExempt", models.BooleanField(default=False)),
                (
                    "placeHolderimageUrl",
                    models.URLField(blank=True, default="", max_length=300, null=True),
                ),
                (
                    "primaryImage",
                    models.ImageField(
                        blank=True, null=True, upload_to="Catalog/PrimaryImages/"
                    ),
                ),
                (
                    "seconaryImage_one",
                    models.ImageField(
                        blank=True, null=True, upload_to="Catalog/SeconaryImages/"
                    ),
                ),
                (
                    "seconaryImage_two",
                    models.ImageField(
                        blank=True, null=True, upload_to="Catalog/SeconaryImages/"
                    ),
                ),
                (
                    "seconaryImage_three",
                    models.ImageField(
                        blank=True, null=True, upload_to="Catalog/SeconaryImages/"
                    ),
                ),
                (
                    "seconaryImage_four",
                    models.ImageField(
                        blank=True, null=True, upload_to="Catalog/SeconaryImages/"
                    ),
                ),
                ("isAvailable", models.BooleanField(db_index=True, default=True)),
                (
                    "clickCount",
                    models.PositiveIntegerField(
                        default=0, help_text="Tracks user engagement"
                    ),
                ),
                ("minimumStockThreshold", models.BigIntegerField(default=4)),
                ("stockQuantity", models.BigIntegerField(default=0)),
                ("reservedQuantity", models.IntegerField(default=0)),
                ("shelfLocationSnapshot", models.TextField(blank=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "soko_merchant_product_catalog",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="MerchantInventoryProductSupplier",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("email", models.CharField(max_length=200, null=True)),
                ("phone", models.CharField(max_length=200, null=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MerchantNotification",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("message", models.TextField()),
                ("resolved", models.BooleanField(default=True)),
                ("urlPath", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MerchantOrder",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "orderID",
                    models.CharField(
                        help_text="Global order reference ID for cross-merchant tracking",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("orderCode", models.CharField(max_length=200, null=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AWAITING_ALLOCATION", "Awaiting System Processing"),
                            ("PREPARING", "Picking & Packing Items"),
                            ("READY_FOR_PICKUP", "Package Ready at Branch Hub"),
                            ("DISPATCHED", "Handed over to Carrier/Rider"),
                            ("DELIVERED", "Successfully Delivered to Customer"),
                            ("CANCELLED", "Order Cancelled"),
                            ("DISPUTED", "Disputed / Hold on Payout"),
                            ("REFUNDED", "Returned & Refunded"),
                        ],
                        db_index=True,
                        default="AWAITING_ALLOCATION",
                        max_length=30,
                    ),
                ),
                (
                    "waybillType",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "waybillNumber",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Tracking code for the logistics dispatch runner (e.g., Sendy, Fargo, Boda rider).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "waybillPhone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "waybillEmail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "waybillName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "isUrgent",
                    models.BooleanField(
                        default=False,
                        help_text="Bypass standard batch queues (e.g., fresh foods, medical essentials)",
                    ),
                ),
                ("isDue", models.BooleanField(default=False, help_text="Due")),
                (
                    "requiresColdChain",
                    models.BooleanField(
                        default=False,
                        help_text="Requires refrigerated dispatch routing",
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=100)),
                (
                    "grossSalesAmount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total revenue generated from items sold",
                        max_digits=12,
                    ),
                ),
                (
                    "shippingAllocation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Shipping fee portion paid out to the vendor if self-fulfilled",
                        max_digits=12,
                    ),
                ),
                (
                    "taxAllocation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Vatable amount collected for this merchant branch",
                        max_digits=12,
                    ),
                ),
                (
                    "commissionPercentageApplied",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Snapshot of the platform take rate applied.",
                        max_digits=5,
                    ),
                ),
                (
                    "platformFeeDeducted",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Platform commission fee deducted from gross sales.",
                        max_digits=12,
                    ),
                ),
                (
                    "netVendorPayout",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        help_text="The final net earnings added to the merchant's withdrawable ledger balance.",
                        max_digits=12,
                    ),
                ),
                (
                    "shippingCustomerName",
                    models.CharField(
                        help_text="Name printed on the packing slip", max_length=255
                    ),
                ),
                (
                    "shippingPhone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "shippingCounty",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shippingTown",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shippingCity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("shippingStreet", models.TextField(null=True)),
                ("shippingBuildingName", models.TextField(null=True)),
                ("nearestIdentifier", models.TextField(null=True)),
                (
                    "shippingPhysicalAddress",
                    models.TextField(
                        help_text="Detailed drop-off coordinates or building/estate details."
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Merchant Order Execution",
                "verbose_name_plural": "Merchant Order Executions",
                "db_table": "soko_merchant_order",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="MerchantOrderItem",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("productTitle", models.CharField(max_length=255)),
                (
                    "productSku",
                    models.CharField(
                        blank=True,
                        help_text="Vendor inventory SKU for picker verification",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("productDescription", models.TextField(null=True)),
                (
                    "shelfLocationSnapshot",
                    models.CharField(
                        blank=True,
                        help_text="Where the picker can locate the item inside the branch hub",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "unitPriceAtSale",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "quantityOrdered",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Order Manifest Item",
                "verbose_name_plural": "Merchant Order Manifest Items",
                "db_table": "soko_merchant_order_item",
            },
        ),
        migrations.CreateModel(
            name="MerchantPayoutLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "linked_order_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the SubOrder that generated this payout",
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=10)),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total revenue generated before cut",
                        max_digits=12,
                    ),
                ),
                (
                    "platform_cut_applied",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The snapshot commissionCutPercent applied",
                        max_digits=5,
                    ),
                ),
                (
                    "net_payout_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount sent to merchant after take rate deduction",
                        max_digits=12,
                    ),
                ),
                ("payout_channel", models.CharField(default="M-Pesa", max_length=30)),
                (
                    "payout_destination",
                    models.CharField(
                        help_text="Paybill/Till Number, Phone Number, or Account Number",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Processing Processing"),
                            ("completed", "Completed Settled"),
                            ("failed", "Failed Reverted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True,
                        help_text="External gateway transaction ID",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for failed/disputed payouts",
                        null=True,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "soko_merchant_payout_ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchantReview",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=255)),
                ("reviewer_email", models.EmailField(max_length=254)),
                (
                    "reviewer_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "soko_merchant_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MpesaPaybillMerchnatPayoutDestination",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(default="M-pesa Paybill", max_length=200)),
                ("paybillNumber", models.CharField(max_length=15, null=True)),
                ("accountNumber", models.CharField(max_length=15, null=True)),
                ("isActive", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MpesaSendMoneyMerchnatPayoutDestination",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(default="M-Pesa Send Money", max_length=200),
                ),
                ("phoneNumber", models.CharField(max_length=15, null=True)),
                ("isActive", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MpesaTillMerchnatPayoutDestination",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(default="M-Pesa Till ", max_length=200)),
                ("tillNumber", models.CharField(max_length=15, null=True)),
                ("isActive", models.BooleanField(default=True)),
            ],
        ),
    ]
