# Generated by Django 5.2.15 on 2026-06-28 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Merchants", "0001_initial"),
        ("taxonomies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="internalmerchantprofile",
            name="vendorOwner",
            field=models.OneToOneField(
                db_column="vendor_owner_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merchant_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="merchantactivitylog",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merchant_initiated_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="merchantactivitylog",
            name="merchant",
            field=models.ForeignKey(
                help_text="The merchant profile tied to this record.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="Merchants.internalmerchantprofile",
            ),
        ),
        migrations.AddField(
            model_name="merchantorder",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_orders",
                to="Merchants.internalmerchantprofile",
            ),
        ),
        migrations.AddField(
            model_name="merchantorderitem",
            name="merchantOrder",
            field=models.ForeignKey(
                db_column="merchant_order_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="manifest_items",
                to="Merchants.merchantorder",
            ),
        ),
        migrations.AddField(
            model_name="merchantpayoutledger",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_history",
                to="Merchants.internalmerchantprofile",
            ),
        ),
        migrations.AddField(
            model_name="merchantproductcatalog",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="taxonomies.brand",
            ),
        ),
        migrations.AddField(
            model_name="merchantproductcatalog",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="taxonomies.category",
            ),
        ),
        migrations.AddField(
            model_name="merchantproductcatalog",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="taxonomies.color",
            ),
        ),
        migrations.AddField(
            model_name="merchantproductcatalog",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="Merchants.internalmerchantprofile",
            ),
        ),
        migrations.AddField(
            model_name="merchantproductcatalog",
            name="searchTags",
            field=models.ManyToManyField(blank=True, to="taxonomies.tag"),
        ),
        migrations.AddField(
            model_name="merchantproductcatalog",
            name="shape",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="taxonomies.shape",
            ),
        ),
        migrations.AddField(
            model_name="merchantproductcatalog",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="taxonomies.size",
            ),
        ),
        migrations.AddField(
            model_name="merchantorderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="historical_merchant_sales",
                to="Merchants.merchantproductcatalog",
            ),
        ),
        migrations.AddField(
            model_name="merchantinventorystock",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_allocations",
                to="Merchants.merchantproductcatalog",
            ),
        ),
        migrations.AddField(
            model_name="merchantstorebranch",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="Merchants.internalmerchantprofile",
            ),
        ),
        migrations.AddField(
            model_name="merchantorder",
            name="fulfillmentBranch",
            field=models.ForeignKey(
                help_text="The specific storefront or regional distribution hub fulfilling this order.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branch_fulfillment_orders",
                to="Merchants.merchantstorebranch",
            ),
        ),
        migrations.AddField(
            model_name="merchantinventorystock",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="Merchants.merchantstorebranch",
            ),
        ),
        migrations.AddIndex(
            model_name="merchantactivitylog",
            index=models.Index(
                fields=["merchant", "category"], name="soko_mercha_merchan_f5218c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchantactivitylog",
            index=models.Index(
                fields=["merchant", "created_at"], name="soko_mercha_merchan_9a5971_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="merchantinventorystock",
            unique_together={("product", "branch")},
        ),
    ]
