# Generated by Django 5.2.15 on 2026-07-14 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailygrosssalessnapshot",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="dailygrosssalessnapshot",
            name="merchant",
        ),
        migrations.RemoveField(
            model_name="merchantactivitylog",
            name="initiated_by",
        ),
        migrations.RemoveField(
            model_name="merchantactivitylog",
            name="merchant",
        ),
        migrations.RemoveField(
            model_name="merchantalert",
            name="Merchant",
        ),
        migrations.RemoveField(
            model_name="merchantinventoryproduct",
            name="productsSuplier",
        ),
        migrations.RemoveField(
            model_name="merchantnotification",
            name="merchant",
        ),
        migrations.RemoveField(
            model_name="merchantorder",
            name="merchant",
        ),
        migrations.RemoveField(
            model_name="merchantorderitem",
            name="merchantOrder",
        ),
        migrations.RemoveField(
            model_name="merchantorderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="merchantpayoutledger",
            name="merchant",
        ),
        migrations.RemoveField(
            model_name="merchantreview",
            name="merchant",
        ),
        migrations.RemoveField(
            model_name="mpesapaybillmerchnatpayoutdestination",
            name="merchant",
        ),
        migrations.RemoveField(
            model_name="mpesasendmoneymerchnatpayoutdestination",
            name="merchant",
        ),
        migrations.RemoveField(
            model_name="mpesatillmerchnatpayoutdestination",
            name="merchant",
        ),
        migrations.AlterField(
            model_name="merchantinventory",
            name="parentMerchant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merchant_inventory",
                to="Merchants.internalmerchantprofile",
            ),
        ),
        migrations.DeleteModel(
            name="BankTransfarMerchnatPayoutDestination",
        ),
        migrations.DeleteModel(
            name="DailyGrossSalesSnapshot",
        ),
        migrations.DeleteModel(
            name="MerchantActivityLog",
        ),
        migrations.DeleteModel(
            name="MerchantAlert",
        ),
        migrations.DeleteModel(
            name="MerchantInventoryProductSupplier",
        ),
        migrations.DeleteModel(
            name="MerchantNotification",
        ),
        migrations.DeleteModel(
            name="MerchantOrder",
        ),
        migrations.DeleteModel(
            name="MerchantOrderItem",
        ),
        migrations.DeleteModel(
            name="MerchantPayoutLedger",
        ),
        migrations.DeleteModel(
            name="MerchantReview",
        ),
        migrations.DeleteModel(
            name="MpesaPaybillMerchnatPayoutDestination",
        ),
        migrations.DeleteModel(
            name="MpesaSendMoneyMerchnatPayoutDestination",
        ),
        migrations.DeleteModel(
            name="MpesaTillMerchnatPayoutDestination",
        ),
    ]
