# Generated by Django 5.2.15 on 2026-07-07 13:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantProductCatalogSupplier",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("email", models.CharField(max_length=200, null=True)),
                ("phone", models.CharField(max_length=200, null=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="branchspecificinventory",
            name="lowStockItems",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="branchspecificinventory",
            name="outOfStockItems",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="branchspecificinventory",
            name="totalInventoryValue",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="merchantproductcatalog",
            name="productsSuplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suplier",
                to="Merchants.merchantproductcatalogsupplier",
            ),
        ),
    ]
