# Generated by Django 5.2.15 on 2026-06-29 02:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTransfarMerchnatPayoutDestination",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(default="Bank Transfar", max_length=200)),
                ("accountNumber", models.CharField(max_length=15, null=True)),
                ("isActive", models.BooleanField(default=True)),
                (
                    "merchnat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_bank_transfar_payout_route",
                        to="Merchants.internalmerchantprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MpesaPaybillMerchnatPayoutDestination",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(default="M-pesa Paybill", max_length=200)),
                ("paybillNumber", models.CharField(max_length=15, null=True)),
                ("accountNumber", models.CharField(max_length=15, null=True)),
                ("isActive", models.BooleanField(default=True)),
                (
                    "merchnat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_mpesa_paybill_payout_route",
                        to="Merchants.internalmerchantprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MpesaSendMoneyMerchnatPayoutDestination",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(default="M-Pesa Send Money", max_length=200),
                ),
                ("phoneNumber", models.CharField(max_length=15, null=True)),
                ("isActive", models.BooleanField(default=True)),
                (
                    "merchnat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_mpesa_payout_route",
                        to="Merchants.internalmerchantprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MpesaTillMerchnatPayoutDestination",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(default="M-Pesa Till ", max_length=200)),
                ("tillNumber", models.CharField(max_length=15, null=True)),
                ("isActive", models.BooleanField(default=True)),
                (
                    "merchnat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_mpesa_till_payout_route",
                        to="Merchants.internalmerchantprofile",
                    ),
                ),
            ],
        ),
    ]
