# Generated by Django 5.2.15 on 2026-06-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0003_banktransfarmerchnatpayoutdestination_and_more"),
        ("taxonomies", "0002_merchantshopcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantstorebranch",
            name="category",
            field=models.ManyToManyField(
                null=True, to="taxonomies.merchantshopcategory"
            ),
        ),
    ]
