# Generated by Django 5.2.15 on 2026-07-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0003_merchantproductcatalogsupplier_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MerchantAlerts",
            new_name="MerchantAlert",
        ),
        migrations.RenameModel(
            old_name="MerchantProductCatalog",
            new_name="MerchantInventoryProduct",
        ),
        migrations.RenameModel(
            old_name="MerchantProductCatalogSupplier",
            new_name="MerchantInventoryProductSupplier",
        ),
        migrations.RenameModel(
            old_name="MerchnatsNotifications",
            new_name="MerchantNotification",
        ),
        migrations.RenameModel(
            old_name="MerchantReviews",
            new_name="MerchantReview",
        ),
        migrations.RenameField(
            model_name="banktransfarmerchnatpayoutdestination",
            old_name="merchnat",
            new_name="merchant",
        ),
        migrations.RenameField(
            model_name="mpesapaybillmerchnatpayoutdestination",
            old_name="merchnat",
            new_name="merchant",
        ),
        migrations.RenameField(
            model_name="mpesasendmoneymerchnatpayoutdestination",
            old_name="merchnat",
            new_name="merchant",
        ),
        migrations.RenameField(
            model_name="mpesatillmerchnatpayoutdestination",
            old_name="merchnat",
            new_name="merchant",
        ),
        migrations.DeleteModel(
            name="GrossSalesSnapshot",
        ),
    ]
