# Generated by Django 5.2.15 on 2026-06-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0004_merchantstorebranch_category"),
        ("taxonomies", "0002_merchantshopcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchantstorebranch",
            name="category",
        ),
        migrations.RemoveField(
            model_name="internalmerchantprofile",
            name="shopCategory",
        ),
        migrations.AddField(
            model_name="internalmerchantprofile",
            name="shopCategory",
            field=models.ManyToManyField(
                null=True, to="taxonomies.merchantshopcategory"
            ),
        ),
    ]
