# Generated by Django 5.2.15 on 2026-07-11 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0005_dailygrosssalessnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchantinventoryproduct",
            name="primaryImage",
            field=models.ImageField(
                blank=True, null=True, upload_to="Catalog/PrimaryImages/"
            ),
        ),
        migrations.AlterField(
            model_name="merchantinventoryproduct",
            name="productsSuplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suplier",
                to="Merchants.merchantinventoryproductsupplier",
            ),
        ),
        migrations.AlterField(
            model_name="merchantinventoryproduct",
            name="seconaryImage_four",
            field=models.ImageField(
                blank=True, null=True, upload_to="Catalog/SeconaryImages/"
            ),
        ),
        migrations.AlterField(
            model_name="merchantinventoryproduct",
            name="seconaryImage_one",
            field=models.ImageField(
                blank=True, null=True, upload_to="Catalog/SeconaryImages/"
            ),
        ),
        migrations.AlterField(
            model_name="merchantinventoryproduct",
            name="seconaryImage_three",
            field=models.ImageField(
                blank=True, null=True, upload_to="Catalog/SeconaryImages/"
            ),
        ),
        migrations.AlterField(
            model_name="merchantinventoryproduct",
            name="seconaryImage_two",
            field=models.ImageField(
                blank=True, null=True, upload_to="Catalog/SeconaryImages/"
            ),
        ),
    ]
