# Generated by Django 5.2.15 on 2026-06-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0005_remove_merchantstorebranch_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalmerchantprofile",
            name="legalDocument",
            field=models.FileField(
                blank=True, null=True, upload_to="merchant_legal_media/"
            ),
        ),
    ]
