# Generated by Django 5.2.15 on 2026-06-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0006_internalmerchantprofile_legaldocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalmerchantprofile",
            name="shopCategoryPersist",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
