# Generated by Django 5.2.15 on 2026-06-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0007_internalmerchantprofile_shopcategorypersist"),
        ("taxonomies", "0002_merchantshopcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalmerchantprofile",
            name="shopCategory",
            field=models.ManyToManyField(to="taxonomies.merchantshopcategory"),
        ),
    ]
