# Generated by Django 5.2.15 on 2026-06-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0008_alter_internalmerchantprofile_shopcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalmerchantprofile",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
