# Generated by Django 5.2.15 on 2026-07-01 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0009_internalmerchantprofile_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrossSalesSnapshot",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "gross_sales_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total revenue generated before any deductions",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_sales_snapshots",
                        to="Merchants.internalmerchantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "soko_merchant_gross_sales_snapshot",
                "ordering": ["-date"],
                "unique_together": {("merchant", "date")},
            },
        ),
    ]
