# Generated by Django 5.2.15 on 2026-07-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0010_grosssalessnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantproductcatalog",
            name="minimumStockThreshhold",
            field=models.BigIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="merchantproductcatalog",
            name="stockAuantity",
            field=models.BigIntegerField(default=0),
        ),
    ]
