# Generated by Django 5.2.15 on 2026-07-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0011_merchantproductcatalog_minimumstockthreshhold_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="merchantproductcatalog",
            old_name="stockAuantity",
            new_name="stockQuantity",
        ),
    ]
