# Generated by Django 5.2.15 on 2026-07-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0012_rename_stockauantity_merchantproductcatalog_stockquantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantproductcatalog",
            name="stockAuantity",
            field=models.BigIntegerField(default=0),
        ),
    ]
