# Generated by Django 5.2.15 on 2026-07-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0013_merchantproductcatalog_stockauantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="merchantstorebranch",
            old_name="is_active",
            new_name="isActive",
        ),
    ]
