# Generated by Django 5.2.15 on 2026-07-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0014_rename_is_active_merchantstorebranch_isactive"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantstorebranch",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
