# Generated by Django 5.2.15 on 2026-07-01 23:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0015_merchantstorebranch_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantAlerts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("system", "System Alert"),
                            ("order", "Order Alert"),
                            ("inventory", "Inventory Alert"),
                            ("payout", "Payout Alert"),
                            ("profile", "Profile Alert"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("Message", models.TextField(blank=True, null=True)),
                (
                    "Priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("Read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_alerts",
                        to="Merchants.internalmerchantprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MerchantReviews",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=255)),
                ("reviewer_email", models.EmailField(max_length=254)),
                (
                    "reviewer_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="Merchants.internalmerchantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "soko_merchant_reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
