# Generated by Django 5.2.15 on 2026-07-02 00:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0016_merchantalerts_merchantreviews"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchantalerts",
            name="id",
        ),
        migrations.AddField(
            model_name="merchantalerts",
            name="unique_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
