# Generated by Django 5.2.15 on 2026-07-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0017_remove_merchantalerts_id_merchantalerts_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantorder",
            name="order_id",
            field=models.CharField(
                default="ORD-SK-3301-VLT-OK",
                help_text="Global order reference ID for cross-merchant tracking",
                max_length=100,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
