# Generated by Django 5.2.15 on 2026-07-02 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0018_merchantorder_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantorder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=datetime.datetime(
                    2026, 7, 2, 0, 42, 20, 914698, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
