# Generated by Django 5.2.15 on 2026-07-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0019_merchantorder_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantproductcatalog",
            name="categoryPersist",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
