# Generated by Django 5.2.15 on 2026-07-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0020_merchantproductcatalog_categorypersist"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantreviews",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
