# Generated by Django 5.2.15 on 2026-07-02 07:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0021_merchantreviews_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchnatsNotifications",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("message", models.TextField()),
                ("resolved", models.BooleanField(default=True)),
                ("urlPath", models.URLField(null=True)),
            ],
        ),
    ]
