# Generated by Django 5.2.15 on 2026-07-02 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0022_merchnatsnotifications"),
    ]

    operations = [
        migrations.RenameField(
            model_name="merchantproductcatalog",
            old_name="isRefubished",
            new_name="isRefurbished",
        ),
        migrations.RenameField(
            model_name="merchantproductcatalog",
            old_name="priceComPetitonRecord",
            new_name="priceCompetitionRecord",
        ),
    ]
