# Generated by Django 5.2.15 on 2026-07-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Merchants",
            "0023_rename_isrefubished_merchantproductcatalog_isrefurbished_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="merchantproductcatalog",
            old_name="minimumStockThreshhold",
            new_name="minimumStockThreshold",
        ),
    ]
