# Generated by Django 5.2.15 on 2026-06-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CustomerMerchantOrders", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MerchantOrderGroup",
        ),
        migrations.DeleteModel(
            name="MerchantOrderItem",
        ),
    ]
