


export const LOCATIONS =[
  { "id": 1, "county": "Mombasa", "code": "MSA", "subcounties": ["Changamwe", "Jomvu", "Kisauni", "Likoni", "Mvita", "Nyali"] },
  { "id": 2, "county": "Kwale", "code": "KWL", "subcounties": ["Kinango", "Lunga Lunga", "Matuga", "Msambweni"] },
  { "id": 3, "county": "Kilifi", "code": "KLF", "subcounties": ["Ganze", "Kaloleni", "Kilifi North", "Kilifi South", "Magarini", "Malindi", "Rabai"] },
  { "id": 4, "county": "Tana River", "code": "TRV", "subcounties": ["Bura", "Galole", "Garsen"] },
  { "id": 5, "county": "Lamu", "code": "LMU", "subcounties": ["Lamu East", "Lamu West"] },
  { "id": 6, "county": "Taita-Taveta", "code": "TVT", "subcounties": ["Mwatate", "Taveta", "Voi", "Wundanyi"] },
  { "id": 7, "county": "Garissa", "code": "GRS", "subcounties": ["Balambala", "Dadaab", "Fafi", "Garissa Township", "Hulugho", "Ijara", "Lagdera"] },
  { "id": 8, "county": "Wajir", "code": "WJR", "subcounties": ["Eldas", "Tarbaj", "Wajir East", "Wajir North", "Wajir South", "Wajir West"] },
  { "id": 9, "county": "Mandera", "code": "MDR", "subcounties": ["Banisa", "Lafey", "Mandera East", "Mandera North", "Mandera South", "Mandera West"] },
  { "id": 10, "county": "Marsabit", "code": "MRS", "subcounties": ["Laisamis", "Moyale", "North Horr", "Saku"] },
  { "id": 11, "county": "Isiolo", "code": "ISL", "subcounties": ["Garbatulla", "Isiolo", "Merti"] },
  { "id": 12, "county": "Meru", "code": "MRU", "subcounties": ["Buuri", "Igembe Central", "Igembe North", "Igembe South", "Central Imenti", "North Imenti", "South Imenti", "Tigania East", "Tigania West"] },
  { "id": 13, "county": "Tharaka-Nithi", "code": "TNT", "subcounties": ["Chuka", "Maara", "Tharaka North", "Tharaka South"] },
  { "id": 14, "county": "Embu", "code": "EMB", "subcounties": ["Manyatta", "Mbeere North", "Mbeere South", "Runyenjes"] },
  { "id": 15, "county": "Kitui", "code": "KTU", "subcounties": ["Kitui Central", "Kitui East", "Kitui Rural", "Kitui South", "Kitui West", "Mwingi Central", "Mwingi North", "Mwingi West"] },
  { "id": 16, "county": "Machakos", "code": "MCK", "subcounties": ["Kangundo", "Kathiani", "Machakos Town", "Masinga", "Matungulu", "Mavoko", "Mwala", "Yatta"] },
  { "id": 17, "county": "Makueni", "code": "MKN", "subcounties": ["Kaiti", "Kibwezi East", "Kibwezi West", "Kilome", "Makueni", "Mbooni"] },
  { "id": 18, "county": "Nyandarua", "code": "NDR", "subcounties": ["Kinangop", "Kipipiri", "Ndaragwa", "Ol Kalou", "Ol Joro Orok"] },
  { "id": 19, "county": "Nyeri", "code": "NYR", "subcounties": ["Kieni East", "Kieni West", "Mathira East", "Mathira West", "Mukurweini", "Nyeri South", "Tetu"] },
  { "id": 20, "county": "Kirinyaga", "code": "KRG", "subcounties": ["Kirinyaga Central", "Kirinyaga East", "Kirinyaga West", "Mwea East", "Mwea West"] },
  { "id": 21, "county": "Murang'a", "code": "MRG", "subcounties": ["Gatanga", "Kahuro", "Kandara", "Kangema", "Kigumo", "Kiharu", "Mathioya", "Murang'a South"] },
  { "id": 22, "county": "Kiambu", "code": "KMB", "subcounties": ["Gatundu North", "Gatundu South", "Githunguri", "Juja", "Kabete", "Kiambaa", "Kiambu", "Kikuyu", "Lari", "Limuru", "Ruiru", "Thika Town"] },
  { "id": 23, "county": "Turkana", "code": "TRK", "subcounties": ["Loima", "Turkana Central", "Turkana East", "Turkana North", "Turkana South", "Turkana West"] },
  { "id": 24, "county": "West Pokot", "code": "WPK", "subcounties": ["North Pokot", "Pokot Central", "Pokot South", "West Pokot"] },
  { "id": 25, "county": "Samburu", "code": "SBR", "subcounties": ["Samburu Central", "Samburu East", "Samburu North"] },
  { "id": 26, "county": "Trans Nzoia", "code": "TNZ", "subcounties": ["Cherangany", "Endebess", "Kiminini", "Kwanza", "Saboti"] },
  { "id": 27, "county": "Uasin Gishu", "code": "UGS", "subcounties": ["Ainabkoi", "Kapseret", "Kesses", "Moiben", "Soy", "Turbo"] },
  { "id": 28, "county": "Elgeyo-Marakwet", "code": "EMK", "subcounties": ["Keiyo North", "Keiyo South", "Marakwet East", "Marakwet West"] },
  { "id": 29, "county": "Nandi", "code": "NDI", "subcounties": ["Aldai", "Chesumei", "Emgwen", "Mosop", "Nandi Hills", "Tinderet"] },
  { "id": 30, "county": "Baringo", "code": "BRG", "subcounties": ["Baringo Central", "Baringo North", "Baringo South", "Eldama Ravine", "Mogotio", "Tiaty"] },
  { "id": 31, "county": "Laikipia", "code": "LKP", "subcounties": ["Laikipia East", "Laikipia North", "Laikipia West"] },
  { "id": 32, "county": "Nakuru", "code": "NKR", "subcounties": ["Bahati", "Gilgil", "Kuresoi North", "Kuresoi South", "Molo", "Naivasha", "Nakuru East", "Nakuru West", "Njoro", "Rongai", "Subukia"] },
  { "id": 33, "county": "Narok", "code": "NRK", "subcounties": ["Narok East", "Narok North", "Narok South", "Narok West", "Trans Mara East", "Trans Mara West"] },
  { "id": 34, "county": "Kajiado", "code": "KJD", "subcounties": ["Isinya", "Kajiado Central", "Kajiado East", "Kajiado North", "Kajiado South", "Kajiado West"] },
  { "id": 35, "county": "Kericho", "code": "KRC", "subcounties": ["Ainamoi", "Belgut", "Bureti", "Kipkelion East", "Kipkelion West", "Soin Sigowet"] },
  { "id": 36, "county": "Bomet", "code": "BMT", "subcounties": ["Bomet Central", "Bomet East", "Chepalungu", "Konoin", "Sotik"] },
  { "id": 37, "county": "Kakamega", "code": "KKG", "subcounties": ["Butere", "Ikolomani", "Khwisero", "Likuyani", "Lugari", "Lurambi", "Malava", "Matungu", "Mumias East", "Mumias West", "Navakholo", "Shinyalu"] },
  { "id": 38, "county": "Vihiga", "code": "VHG", "subcounties": ["Emuhaya", "Hamisi", "Luanda", "Sabatia", "Vihiga"] },
  { "id": 39, "county": "Bungoma", "code": "BGM", "subcounties": ["Bumula", "Kabuchai", "Kanduyi", "Kimilili", "Mt Elgon", "Sirisia", "Tongaren", "Webuye East", "Webuye West"] },
  { "id": 40, "county": "Busia", "code": "BSA", "subcounties": ["Budalangi", "Butula", "Funyula", "Matayos", "Nambale", "Teso North", "Teso South"] },
  { "id": 41, "county": "Siaya", "code": "SYA", "subcounties": ["Alego Usonga", "Bondo", "Gem", "Rarieda", "Ugenya", "Ugunja"] },
  { "id": 42, "county": "Kisumu", "code": "KSM", "subcounties": ["Kisumu Central", "Kisumu East", "Kisumu West", "Muhoroni", "Nyakach", "Nyando", "Seme"] },
  { "id": 43, "county": "Homa Bay", "code": "HBY", "subcounties": ["Homa Bay Town", "Kabondo Kasipul", "Karachuonyo", "Kasipul", "Mbita", "Ndhiwa", "Rangwe", "Suba"] },
  { "id": 44, "county": "Migori", "code": "MGR", "subcounties": ["Awendo", "Kuria East", "Kuria West", "Nyatike", "Rongo", "Suna East", "Suna West", "Uriri"] },
  { "id": 45, "county": "Kisii", "code": "KSI", "subcounties": ["Bobasi", "Bomachoge Borabu", "Bomachoge Chache", "Bonchari", "Kitutu Chache North", "Kitutu Chache South", "Nyaribari Chache", "Nyaribari Masaba", "South Mugirango"] },
  { "id": 46, "county": "Nyamira", "code": "NMR", "subcounties": ["Borabu", "Manga", "Masaba North", "Nyamira North", "Nyamira South"] },
  { "id": 47, "county": "Nairobi", "code": "NBI", "subcounties": ["Dagoretti North", "Dagoretti South", "Embakasi Central", "Embakasi East", "Embakasi North", "Embakasi South", "Embakasi West", "Kamukunji", "Kasarani", "Kibra", "Lang'ata", "Makadara", "Mathare", "Njiru", "Roysambu", "Ruaraka", "Starehe", "Westlands"] }
]
