# Generated by Django 5.2.15 on 2026-06-29 02:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantShopCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
