# Generated by Django 5.2.15 on 2026-07-13 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="New Chat", max_length=255)),
                ("pinned", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                (
                    "is_protected",
                    models.BooleanField(db_column="protected", default=False),
                ),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                            ("sokoAI", "SokoAI"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                ("timestamp", models.BigIntegerField()),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("inquiry", "Inquiry"),
                            ("error", "Error"),
                            ("followup", "Followup"),
                            ("response", "Response"),
                            ("search", "Search"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "search_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct_search", "Direct Search"),
                            ("intelligent_search", "Intelligent Search"),
                            ("direct_filter", "Direct Filter"),
                            ("intelligent_filter", "Intelligent Filter"),
                            ("direct_followup", "Direct Followup"),
                            ("intelligent_followup", "Intelligent Followup"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct_response", "Direct Response"),
                            ("intelligent_response", "Intelligent Response"),
                            ("direct_followup", "Direct Followup"),
                            ("intelligent_followup", "Intelligent Followup"),
                            ("direct_inquiry", "Direct Inquiry"),
                            ("intelligent_inquiry", "Intelligent Inquiry"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("streamed", models.BooleanField(default=False)),
                ("products", models.JSONField(blank=True, default=list)),
                (
                    "related_products",
                    models.JSONField(
                        blank=True, db_column="relatedProducts", default=list
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
