# Generated by Django 5.2.15 on 2026-07-03 08:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Merchants", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="New Search Loop", max_length=255)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("continent", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "city",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "timezone_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer Not To Say"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("is_customer", models.BooleanField(default=True)),
                ("is_merchant", models.BooleanField(db_index=True, default=False)),
                (
                    "is_merchant_verified",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("is_banned", models.BooleanField(default=False)),
                ("is_suspended", models.BooleanField(default=False)),
                ("is_blocked", models.BooleanField(default=False)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("is_phone_verified", models.BooleanField(default=False)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("preferred_language", models.CharField(default="en", max_length=20)),
                ("last_prompt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("failed_login_attempts", models.PositiveIntegerField(default=0)),
                ("last_password_change", models.DateTimeField(blank=True, null=True)),
                ("is_current_login_verified", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("mfa_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CartGroup",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("protected", models.BooleanField(default=False)),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cart_group",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCart",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "cart_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_carts",
                        to="users.cartgroup",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_carts_related_merchant",
                        to="Merchants.internalmerchantprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCartItem",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "product_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("product_description", models.TextField(blank=True, null=True)),
                ("count", models.PositiveIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cart_items",
                        to="Merchants.merchantproductcatalog",
                    ),
                ),
                (
                    "sub_cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="users.subcart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication & Security"),
                            ("profile", "Profile & Settings Modification"),
                            ("branch", "Branch Distribution Operations"),
                            ("catalog", "Inventory & Catalog Updates"),
                            ("order", "Order & Fulfillment Triggers"),
                            ("payin", "Financials & Ledger Settlements"),
                            ("system", "System Automation / Background Alert"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("warning", "Warning Notice"),
                            ("critical", "Critical Security/Financial"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=15,
                    ),
                ),
                (
                    "action_event",
                    models.CharField(
                        help_text="e.g., 'user_login', 'user_signup' ", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable detail statement summarizing exactly what transpired."
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser/device fingerprint data",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "location_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Approximate or pinpoint geo-metadata at the moment of entry, e.g., 'Juja, Kiambu'",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_initiated_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user  tied to this record.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity Log",
                "verbose_name_plural": "User Activity Logs",
                "db_table": "soko_user_activity_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Address",
                "verbose_name_plural": "User Addresses",
            },
        ),
        migrations.CreateModel(
            name="UserAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAlertItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("price_drop", "Price Drop Watch"),
                            ("stock_status", "Back In Stock"),
                            ("promo_code", "Flash Promotional Code"),
                            ("system", "System Notifications"),
                            ("security", "Security Alerts"),
                        ],
                        default="price_drop",
                        max_length=50,
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target budget match value in KSh",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("is_triggered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="users.useralert",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_alerts",
                        to="Merchants.merchantproductcatalog",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserConversationHistoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("user_query", models.JSONField()),
                ("ai_system_response", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_history",
                        to="users.userconversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserOrderGroup",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING_FOR_PAYMENT", "Waiting for Payment to process"),
                            ("QUEUED", "Order Queued for Processing"),
                            ("PROCESSING", "Order Being Processed"),
                            ("IN_SHIPMENT", "Order in shipment"),
                            ("DELAYED_IN_SHIPMENT", "Order Delaying in shipment"),
                            ("DELIVERED", "Order Delivered"),
                        ],
                        default="WAITING_FOR_PAYMENT",
                        max_length=30,
                    ),
                ),
                ("order_delivered", models.BooleanField(default=False)),
                ("order_delivery_confirmed", models.BooleanField(default=False)),
                ("order_disputed", models.BooleanField(default=False)),
                ("order_cancelled", models.BooleanField(default=False)),
                ("tracking_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "delivery_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="users.useraddress",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPaymentOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa Express"),
                            ("bank", "Bank-Transfer"),
                            ("card", "Debit/Credit Card"),
                        ],
                        default="mpesa",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "mpesa_phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Format: 07XXXXXXXX or 254XXXXXXXX",
                        max_length=15,
                        null=True,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "bank_account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "card_brand",
                    models.CharField(
                        blank=True,
                        help_text="Visa, Mastercard, etc.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "card_last_four",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "card_expiry_mask",
                    models.CharField(
                        blank=True, help_text="MM/YYYY", max_length=7, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_options",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserReviewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_text", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="users.userreview",
                    ),
                ),
                (
                    "target_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to="Merchants.merchantproductcatalog",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSearches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "eligible",
                    models.BooleanField(
                        default=True,
                        help_text="Global flag determining if the user can execute search requests.",
                    ),
                ),
                (
                    "is_on_free_tier",
                    models.BooleanField(
                        default=True,
                        help_text="True if on complimentary search credits; False if upgraded to premium limits.",
                    ),
                ),
                (
                    "free_tier_search_limit",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="The total maximum free searches granted by default.",
                    ),
                ),
                (
                    "current_tier_use",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Tracks active search computations performed in the current billing cycle.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Search Profile",
                "verbose_name_plural": "User Search Profiles",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="userconversation",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="users.usersearches",
            ),
        ),
        migrations.CreateModel(
            name="UserShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "address_tag",
                    models.CharField(
                        choices=[
                            ("home", "Home / Residence"),
                            ("office", "Office / Workplace"),
                            ("pickup", "Pickup Station Hub"),
                        ],
                        default="home",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "full_name",
                    models.CharField(help_text="Recipient Name", max_length=255),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Contact number for courier deliveries", max_length=15
                    ),
                ),
                (
                    "building_or_estate",
                    models.CharField(
                        help_text="e.g., Greenwood Apartments, Block B / Delta Corner",
                        max_length=255,
                    ),
                ),
                (
                    "street_or_road",
                    models.CharField(
                        help_text="e.g., Kilimanjaro Avenue / Waiyaki Way",
                        max_length=255,
                    ),
                ),
                (
                    "area_or_estate",
                    models.CharField(
                        help_text="e.g., Kilimani / Westlands", max_length=100
                    ),
                ),
                ("city", models.CharField(default="Nairobi", max_length=100)),
                ("country", models.CharField(default="Kenya", max_length=100)),
                (
                    "delivery_instructions",
                    models.TextField(
                        blank=True,
                        help_text="e.g., Leave with reception, call upon arrival.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Shipping Address",
                "verbose_name_plural": "User Shipping Addresses",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSubOrder",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("order_is_urgent", models.BooleanField(default=False)),
                ("express_delivery", models.BooleanField(default=False)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_orders_rlated_merchant",
                        to="Merchants.internalmerchantprofile",
                    ),
                ),
                (
                    "order_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_orders",
                        to="users.userordergroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSubOrderItem",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "product_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("product_description", models.TextField(blank=True, null=True)),
                ("count", models.PositiveIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="Merchants.merchantproductcatalog",
                    ),
                ),
                (
                    "sub_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="users.usersuborder",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="users_user_phone_9474e8_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_merchant"], name="users_user_is_merc_4e92b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["country"], name="users_user_country_7f9bdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["city"], name="users_user_city_2e3e9b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["created_at"], name="users_user_created_cf865c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subcart",
            unique_together={("cart_group", "merchant")},
        ),
        migrations.AlterUniqueTogether(
            name="subcartitem",
            unique_together={("sub_cart", "product")},
        ),
    ]
