# Generated by Django 5.2.16 on 2026-08-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="allow_phone_pings",
            new_name="allow_order_dispatch_checkpoints_alerts",
        ),
        migrations.AddField(
            model_name="user",
            name="allow_location_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="allow_messages_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="allow_payment_receipt_alert",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="allow_sms_tracking_pings",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="ip_address_history",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="password_recovery_code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
