# Generated by Django 5.2.15 on 2026-06-29 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication & Security"),
                            ("profile", "Profile & Settings Modification"),
                            ("branch", "Branch Distribution Operations"),
                            ("catalog", "Inventory & Catalog Updates"),
                            ("order", "Order & Fulfillment Triggers"),
                            ("payin", "Financials & Ledger Settlements"),
                            ("system", "System Automation / Background Alert"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("warning", "Warning Notice"),
                            ("critical", "Critical Security/Financial"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=15,
                    ),
                ),
                (
                    "action_event",
                    models.CharField(
                        help_text="e.g., 'user_login', 'user_signup' ", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable detail statement summarizing exactly what transpired."
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser/device fingerprint data",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "location_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Approximate or pinpoint geo-metadata at the moment of entry, e.g., 'Juja, Kiambu'",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_initiated_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user  tied to this record.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity Log",
                "verbose_name_plural": "User Activity Logs",
                "db_table": "soko_user_activity_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
