# Generated by Django 5.2.15 on 2026-06-09 10:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAlertItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("price_drop", "Price Drop Watch"),
                            ("stock_status", "Back In Stock"),
                            ("promo_code", "Flash Promotional Code"),
                            ("system", "System Notifications"),
                            ("security", "Security Alerts"),
                        ],
                        default="price_drop",
                        max_length=50,
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target budget match value in KSh",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("is_triggered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="users.useralert",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_alerts",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPaymentOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa Express"),
                            ("card", "Debit/Credit Card"),
                        ],
                        default="mpesa",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "mpesa_phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Format: 07XXXXXXXX or 254XXXXXXXX",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        blank=True,
                        help_text="Visa, Mastercard, etc.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "card_last_four",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "card_expiry_mask",
                    models.CharField(
                        blank=True, help_text="MM/YYYY", max_length=7, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_options",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserReviewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_text", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="users.userreview",
                    ),
                ),
                (
                    "target_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "address_tag",
                    models.CharField(
                        choices=[
                            ("home", "Home / Residence"),
                            ("office", "Office / Workplace"),
                            ("pickup", "Pickup Station Hub"),
                        ],
                        default="home",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "full_name",
                    models.CharField(help_text="Recipient Name", max_length=255),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Contact number for courier deliveries", max_length=15
                    ),
                ),
                (
                    "building_or_estate",
                    models.CharField(
                        help_text="e.g., Greenwood Apartments, Block B / Delta Corner",
                        max_length=255,
                    ),
                ),
                (
                    "street_or_road",
                    models.CharField(
                        help_text="e.g., Kilimanjaro Avenue / Waiyaki Way",
                        max_length=255,
                    ),
                ),
                (
                    "area_or_estate",
                    models.CharField(
                        help_text="e.g., Kilimani / Westlands", max_length=100
                    ),
                ),
                ("city", models.CharField(default="Nairobi", max_length=100)),
                ("country", models.CharField(default="Kenya", max_length=100)),
                (
                    "delivery_instructions",
                    models.TextField(
                        blank=True,
                        help_text="e.g., Leave with reception, call upon arrival.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Shipping Address",
                "verbose_name_plural": "User Shipping Addresses",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
    ]
