# Generated by Django 5.2.15 on 2026-06-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_required",
            field=models.BooleanField(default=False),
        ),
    ]
