# Generated by Django 5.2.15 on 2026-07-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserActivityLog",
        ),
    ]
