# Generated by Django 5.2.15 on 2026-07-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_delete_useractivitylog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_current_login_verified",
            new_name="is_flagged",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_merchant_verified",
            new_name="is_merchant_account_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_prompt_at",
        ),
        migrations.AddField(
            model_name="user",
            name="account_validation_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="allow_email_notification",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="allow_phone_notification",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="allow_phone_pings",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="allow_push_notification",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="allow_whatsApp_dispatch_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="apartment_door_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="county",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="estate_area_neighborhood",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="flag_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_eligible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="national_id_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="street",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sub_county",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
