# Generated by Django 5.2.15 on 2026-06-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merchants", "0008_alter_internalmerchantprofile_shopcategory"),
        ("users", "0002_useractivitylog"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderGroup",
            new_name="UserOrderGroup",
        ),
        migrations.RenameModel(
            old_name="SubOrder",
            new_name="UserSubOrder",
        ),
        migrations.RenameModel(
            old_name="SubOrderItem",
            new_name="UserSubOrderItem",
        ),
        migrations.RemoveField(
            model_name="userorderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="userorderitem",
            name="product",
        ),
        migrations.AddField(
            model_name="userpaymentoption",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userpaymentoption",
            name="bank_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="userpaymentoption",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("mpesa", "M-Pesa Express"),
                    ("bank", "Bank-Transfer"),
                    ("card", "Debit/Credit Card"),
                ],
                default="mpesa",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="UserOrder",
        ),
        migrations.DeleteModel(
            name="UserOrderItem",
        ),
    ]
