# Generated by Django 5.2.16 on 2026-07-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_is_current_login_verified_user_is_flagged_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="continent",
            field=models.CharField(default="Africa", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(db_index=True, default="Kenya", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="country_code",
            field=models.CharField(default="254", max_length=10),
        ),
    ]
