# Generated by Django 5.2.16 on 2026-07-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_continent_alter_user_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location_explanation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
