# Generated by Django 5.2.15 on 2026-06-10 03:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Country Name"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="ZIP / Postal Code",
                    ),
                ),
                (
                    "is_setup_for_operation",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Operational"
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="color",
            options={
                "ordering": ["name"],
                "verbose_name": "Color",
                "verbose_name_plural": "Colors",
            },
        ),
        migrations.AlterModelOptions(
            name="shape",
            options={
                "ordering": ["name"],
                "verbose_name": "Shape",
                "verbose_name_plural": "Shapes",
            },
        ),
        migrations.AlterModelOptions(
            name="size",
            options={
                "ordering": ["name"],
                "verbose_name": "Size",
                "verbose_name_plural": "Sizes",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, unique=True, verbose_name="Brand Name"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="related_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Categories commonly associated or recommended with this item matrix.",
                to="inventory.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="color",
            name="hex_code",
            field=models.CharField(
                blank=True,
                help_text="e.g., #FFFFFF or #000000",
                max_length=7,
                null=True,
                verbose_name="HEX Code",
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="Color Name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Product Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="inventory_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Stock Inventory Count"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Is Active / Visible"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Current Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                db_index=True,
                max_length=100,
                unique=True,
                verbose_name="SKU Reference ID",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Product Title"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="shape",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="Shape Value"
            ),
        ),
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(
                db_index=True, max_length=50, unique=True, verbose_name="Size Value"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                db_index=True, max_length=50, unique=True, verbose_name="Tag String"
            ),
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Currency Name"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(max_length=20, verbose_name="Currency Symbol"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        default="KES",
                        max_length=10,
                        unique=True,
                        verbose_name="ISO Currency Code",
                    ),
                ),
                (
                    "is_allowed",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is Allowed / Active"
                    ),
                ),
                (
                    "is_base_currency",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="System anchor currency used for calculating global conversion rate metrics.",
                        verbose_name="Is Base Currency",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="The primary economic region utilizing this currency asset.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="currencies",
                        to="inventory.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Marketplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        unique=True,
                        verbose_name="Marketplace Title",
                    ),
                ),
                ("base_url", models.URLField(unique=True, verbose_name="Base URL")),
                (
                    "direct_search_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Direct Search URL",
                    ),
                ),
                (
                    "categorised_search_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Categorized Search URL",
                    ),
                ),
                (
                    "brand_based_search_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Brand Search URL",
                    ),
                ),
                (
                    "product_structure",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Product Structure Configuration",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Operational country boundary for pricing and regional logistics configurations.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplaces",
                        to="inventory.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace",
                "verbose_name_plural": "Marketplaces",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="marketplace",
            field=models.ForeignKey(
                help_text="The marketplace where this item record was parsed and extracted from.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="inventory.marketplace",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="inventory_p_categor_471092_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["marketplace", "is_active"],
                name="inventory_p_marketp_03a458_idx",
            ),
        ),
    ]
