# Generated by Django 5.2.15 on 2026-07-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_roles",
                    models.JSONField(
                        default=list,
                        help_text="List of roles assigned to this administrator",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("department", models.CharField(default="Operations", max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "duration_in_the_company",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("age", models.IntegerField(default=18)),
                ("ethnicity", models.CharField(default="Not Specified", max_length=50)),
                ("country_of_birth", models.CharField(default="Kenya", max_length=100)),
                ("is_allowed_access", models.BooleanField(default=True)),
                ("is_registration_verified", models.BooleanField(default=False)),
                ("is_phone_verified", models.BooleanField(default=False)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("is_identity_verified", models.BooleanField(default=False)),
                ("two_factor_enforced", models.BooleanField(default=False)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("trusted_machine_seeds", models.JSONField(blank=True, default=list)),
                (
                    "login_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of recent login ISO timestamps",
                    ),
                ),
                (
                    "ui_theme_preference",
                    models.CharField(default="dark", max_length=10),
                ),
                (
                    "default_dashboard_view",
                    models.CharField(default="general_view", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
